<?
$PERM["personal"]["2"]="D";
$PERM["personal"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["404.php"]["7"]="W";
$PERM[".top.menu.php"]["7"]="W";
$PERM[".bottom.menu.php"]["7"]="W";
$PERM["upload"]["7"]="W";
$PERM["search"]["7"]="W";
$PERM["include_areas"]["7"]="W";
$PERM["company"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["auth"]["7"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["pub"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["/"]["*"]="R";
?>